project:
  type: website
  output-dir: docs

website:
  title: "Applied Systems Ecology"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - text: Research
            href: research.qmd
          - text: Projects
            href: projects.qmd
      - people.qmd
      - publications.qmd
      - news.qmd
      - join.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

