project:
  type: website
  output-dir: docs

website:
  title: "Applied Systems Ecology Lab"
  back-to-top-navigation: true
  page-footer:
    center: "Â© 2026 Applied Systems Ecology Lab"
    background: light

  navbar:
    background: primary
    logo: "lab_icon.png"
    search: true
    pinned: true
    tools:
      - icon: github
        href: https://github.com/AppliedSystemsEcology
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        menu:
          - text: "Mission"
            href: about.qmd
          - text: "Lab Expectations"
            href: about.qmd
      - text: "People"
        menu:
          - text: "Primary Investigator"
            href: people.html#principal-investigator
          - text: "Extension Faculty"
            href: people.html#extension-faculty
          - text: "Postdoctoral Fellows"
            href: people.html#postdoctoral-fellows
          - text: "Graduate Students"
            href: people.html#graduate-students
          - text: "Technicians"
            href: people.html#technicians
          - text: "Undergraduate Students"
            href: people.html#undergraduate-students
          - text: "Alumni"
            href: people.html#alumni
      - text: "Projects"
        menu:
          - text: "Project 1"
            href: projects.html#project-1
          - text: "Project 2"
            href: projects.html#project-2
          - text: "Project 3"
            href: projects.html#project-3
      - text: "Publications"
        href: publications.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "News"
        href: news.qmd
      - text: "Join the Lab"
        href: join.qmd

format:
  html:
    theme:
       - brite-theme.scss
    toc: true


editor: visual

