project:
  type: website
  output-dir: docs

website:
  title: "Applied Systems Ecology Lab"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - people.qmd
      - projects.qmd
      - publications.qmd
      - outreach.qmd
      - news.qmd
      - join.qmd

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true

editor: visual

