project:
  type: website
  output-dir: docs

website:
  title: "Applied Systems Ecology Lab"
  back-to-top-navigation: true

  navbar:
    background: primary
    logo: "lab_icon.png"
    search: true
    pinned: true
    tools:
      - icon: github
        href: https://github.com/AppliedSystemsEcology
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        menu:
          - text: "Mission"
            href: about.qmd
      - text: "People"
        menu:
          - text: "Primary Investigator"
            href: people.qmd
          - text: "Postdoctoral Fellows"
            href: people.qmd
          - text: "Graduate Students"
            href: people.qmd
          - text: "Undergraduate Students"
            href: people.qmd
          - text: "Technicians"
            href: people.qmd
          - text: "Alumni"
            href: people.qmd
      - text: "Projects"
        menu:
          - text: "Project 1"
            href: projects.qmd
          - text: "Project 2"
            href: projects.qmd
          - text: "Project 3"
            href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "News"
        href: news.qmd
      - text: "Join the Lab"
        href: join.qmd

format:
  html:
    theme:
       - brite-theme.scss
    toc: true

editor: visual

